<?php
// module/Album/view/division/division/add.phtml:

$title = 'Add new division';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('division', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));
echo $this->formRow($form->get('name'));
echo $this->formRow($form->get('content'));
echo $this->formRow($form->get('url'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();