<?php
// module/Division/view/giftcard/giftcard/delete.phtml:

$title = 'Delete Division';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>

<p>Are you sure that you want to delete
    '<?php echo $this->escapeHtml($division->name); ?>' by
    '<?php echo $this->escapeHtml($division->price); ?>'?
    '<?php echo $this->escapeHtml($division->url); ?>'?
</p>
<?php
$url = $this->url('division', array(
    'action' => 'delete',
    'id'     => $this->id,
));
?>
<form action="<?php echo $url; ?>" method="post">
    <div>
        <input type="hidden" name="id" value="<?php echo (int) $division->id; ?>" />
        <input type="submit" name="del" value="Yes" />
        <input type="submit" name="del" value="No" />
    </div>
</form>

