<?php
// module/Album/view/division/division/index.phtml:

$title = 'My divisions';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('division', array('action'=>'add'));?>">Add new division</a>
</p>

<table class="table">
    <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>url</th>
        <th>&nbsp;</th>
    </tr>
    <?php print_r(count($divisions)); ?>
    <?php echo $name; ?>

    <?php foreach ($divisions as $division) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($division->name);?></td>
            <td><?php echo $this->escapeHtml($division->content);?></td>
            <td><?php echo $this->escapeHtml($division->url);?></td>
            <td>
                <a href="<?php echo $this->url('division',
                    array('action'=>'edit', 'id' => $division->id));?>">Edit</a>
                <a href="<?php echo $this->url('division',
                    array('action'=>'delete', 'id' => $division->id));?>">Delete</a>
            </td>

        </tr>

    <?php endforeach; ?>
</table>