<?php
// module/AlbumImage/view/album_image/album_image/add.phtml:

$title = 'Add new album_image';
$this->headTitle($title);
?>
    <h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('album_image', array('action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
echo $this->formHidden($form->get('id'));

//echo $this->formRow($form->get('number'));
echo $this->formRow($form->get('album_id'));

echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();