<?php
// module/Album/view/album_image/album_image/index.phtml:

$title = 'My album_images';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<p>
    <a href="<?php echo $this->url('album_image', array('action'=>'add'));?>">Add new album_image</a>
</p>

<table class="table">
    <tr>
        <th>Album Id</th>
        <th>created_at</th>
        <th>Album id</th>
        <th>&nbsp;</th>
    </tr>
    <?php print_r(count($album_images)); ?>
    <?php echo $name; ?>

    <?php foreach ($album_images as $album_image) : ?>
        <tr>
            <td><?php echo $this->escapeHtml($album_image->name);?></td>
            <td><?php echo $this->escapeHtml($album_image->created_at);?></td>
            <td><?php echo $this->escapeHtml($album_image->title);?></td>
            <td>
                <a href="<?php echo $this->url('album_image',
                    array('action'=>'edit', 'id' => $album_image->id));?>">Edit</a>
                <a href="<?php echo $this->url('album_image',
                    array('action'=>'delete', 'id' => $album_image->id));?>">Delete</a>
            </td>

        </tr>

    <?php endforeach; ?>
</table>
